# Generated by Django 3.1.3 on 2020-11-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='time_needed',
            field=models.PositiveIntegerField(max_length=50),
        ),
    ]
