# Generated by Django 3.1.3 on 2020-11-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_auto_20201110_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='time_needed',
            field=models.PositiveIntegerField(),
        ),
    ]
